name: CI

on:
    push:
    pull_request:
      branches: [ "master" ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Clone GoogleTest
          run: git submodule update --init

        - name: Build
          working-directory: ./test
          run: |
            cmake -S . -B build
            cmake --build build

        - name: Run tests
          working-directory: ./test/build
          run: ctest
